FROM debian:buster

RUN uname -a
RUN apt update && apt install -y wget curl git build-essential flex bison autoconf automake libmpfr-dev libgmp-dev libmpc-dev texinfo libncurses5-dev && git clone https://github.com/dinuxbg/gnupru.git && apt clean
WORKDIR /gnupru
ENV PREFIX=/usr/pru-gcc
RUN ./download-and-patch.sh && ./build.sh
ENV PATH="${PATH}:/usr/pru-gcc/bin"
RUN pru-gcc -v && rm ../gnupru -rf
